name: Hourly cron

on:
  schedule:
    - cron: "0 * * * *"  # kas valandą
  workflow_dispatch:      # leidžia paleisti rankiniu būdu

jobs:
  hourly-task:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Healthcheck GitHub Pages repo endpoints
        env:
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
        run: |
          set -euo pipefail
          BASE="https://${OWNER}.github.io/${REPO}"
          echo "Checking: $BASE"

          check() {
            local url="$1"
            # retry a bit to avoid transient CDN/Pages hiccups
            for i in 1 2 3; do
              if curl -fsSIL --max-time 20 "$url" >/dev/null; then
                return 0
              fi
              sleep 5
            done
            return 1
          }

          FAIL=0
          check "$BASE/index.html" || FAIL=1

          # APT (stable is required; other dists are aliases)
          check "$BASE/apt/dists/stable/Release" || FAIL=1
          check "$BASE/apt/dists/stable/main/binary-amd64/Packages.gz" || FAIL=1
          check "$BASE/apt/dists/stable/main/binary-arm64/Packages.gz" || FAIL=1

          # Common alias (Ubuntu 24.04)
          check "$BASE/apt/dists/noble/Release" || FAIL=1

          # RPM
          check "$BASE/rpm/x86_64/repodata/repomd.xml" || FAIL=1
          check "$BASE/rpm/aarch64/repodata/repomd.xml" || FAIL=1

          if [[ "$FAIL" == "0" ]]; then
            echo "Healthcheck OK"
            exit 0
          fi

          echo "Healthcheck FAILED"
          exit 2

      - name: Trigger repo rebuild/deploy if broken
        if: ${{ failure() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          echo "Triggering update-repos workflow dispatch..."
          curl -fsSL -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/update-repos.yml/dispatches" \
            -d '{"ref":"main"}'
          echo "Dispatched update-repos.yml"
